version: "3"
services:
  db:
    container_name: starwars-api-db
    restart: always
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
